name = "BmlipTeachingTools"
uuid = "656a7065-6f73-6c65-7465-6e646e617262"
authors = ["Fons van der Plas <f.o.v.d.plas@tue.nl>"]
version = "1.4.0"

[deps]
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
HypertextLiteral = "0.9"
InteractiveUtils = "<0.0.1,0.1,1"
Markdown = "<0.0.01,0.1,1"
PlutoTeachingTools = "0.4.4"
PlutoUI = "0.7.69"
Reexport = "1"
julia = "1.10"


[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]

